[workspace]
authors = ["Suzanne Scott <23192453+szsctt@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "sewing-optimiser"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
layout = "python -m sewing_optimiser.cli"
test = "python -m pytest"
app = "python -m sewing_optimiser.server"

[dependencies]
python = "3.12.*"
pymupdf = ">=1.28.0,<2"
shapely = ">=2.1.2,<3"
pytest = ">=9.1.1,<10"
scipy = ">=1.18.1,<2"
pillow = ">=12.3.0,<13"
numpy = ">=2.5.3,<3"
fastapi = ">=0.141.1,<0.142"
uvicorn = ">=0.53.0,<0.54"
